version: "3.9"

services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  play-scout:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4500:4500"
    volumes:
      - .:/app           # Sync current directory to /app in container
    command: npm run dev

volumes:
  pgdata:
